// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx1P-bHV4jpn9G6088vEjdQCYJ4IlJ_YM',
    appId: '1:105725100498:web:1d04908aa27da734e2880b',
    messagingSenderId: '105725100498',
    projectId: 'recall-pro-8d0f4',
    authDomain: 'recall-pro-8d0f4.firebaseapp.com',
    storageBucket: 'recall-pro-8d0f4.firebasestorage.app',
    measurementId: 'G-DF1VTEWC34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0i527a03YbL-K0fo4Psc_qeyboZLOYWw',
    appId: '1:105725100498:android:5f71e64cfebd3882e2880b',
    messagingSenderId: '105725100498',
    projectId: 'recall-pro-8d0f4',
    storageBucket: 'recall-pro-8d0f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-wmGWggJBu3X6n9sq9b9GMpgMm3UuvGI',
    appId: '1:105725100498:ios:76eda59fd755137de2880b',
    messagingSenderId: '105725100498',
    projectId: 'recall-pro-8d0f4',
    storageBucket: 'recall-pro-8d0f4.firebasestorage.app',
    iosBundleId: 'com.example.recallPro',
  );
}
